module.exports = [
    "/ declare featureGroup_01 \\",
    /**/"/ declare feature_01 \\",
    /*  */"/ declare f01_steps_01 \\",
    "fg_01.before",
    "fg_01_f_01.before",
    /*      */"=> it given",
    /*      */"=> it when",
    /*      */"=> it then",
    "fg_01_f_01.after",
    "fg_01.after",
    /*  */"\\ declare f01_steps_01 /",

    /*  */"/ declare f01_steps_02 \\",
    "fg_01.before",
    "fg_01_f_01.before",
    "fg01_s02.before",
    /*      */"=> it given",
    /*      */"=> it given and",
    /*      */"=> it then",
    "fg01_s02.after",
    "fg_01_f_01.after",
    "fg_01.after",
    /*  */"\\ declare f01_steps_02 /",

    /*  */"/ declare f01_steps_03 \\",
    "fg_01.before",
    "fg_01_f_01.before",
    /*      */"=> it when",
    /*      */"=> it when and",
    /*      */"=> it then",
    "fg_01_f_01.after",
    "fg_01.after",
    /*  */"\\ declare f01_steps_03 /",

    /*  */"/ declare f01_steps_04 \\",
    "fg_01.before",
    "fg_01_f_01.before",
    /*      */"=> it then",
    /*      */"=> it then and",
    "fg_01_f_01.after",
    "fg_01.after",
    /*  */"\\ declare f01_steps_04 /",

    /*  */"/ declare f01_steps_05 \\",
    "fg_01.before",
    "fg_01_f_01.before",
    /*      */"=> it given",
    /*      */"=> it given and",
    /*      */"=> it given and",
    /*      */"=> it when",
    /*      */"=> it then",
    /*      */"=> it then and",
    "fg_01_f_01.after",
    "fg_01.after",
    /*  */"\\ declare f01_steps_05 /",

    /**/"\\ declare feature_01 /",


    /**/"/ declare feature_02 \\",
    /*  */"/ declare f02_steps_01 \\",
    "fg_01.before",
    /*      */"=> xit when",
    /*      */"=> it when and",
    /*      */"=> it then",
    "fg_01.after",
    /*  */"\\ declare f02_steps_01 /",

    /*  */"/ declare f02_steps_02 \\",
    "fg_01.before",
    /*      */"=> it when",
    /*      */"=> xit when and",
    /*      */"=> it when and",
    /*      */"=> it then",
    "fg_01.after",
    /*  */"\\ declare f02_steps_02 /",

    /*  */"/ declare f02_steps_03 \\",
    "fg_01.before",
    /*      */"=> it when",
    /*      */"=> xit then",
    /*      */"=> it then and",
    "fg_01.after",
    /*  */"\\ declare f02_steps_03 /",

    /*  */"/ declare f02_steps_04 \\",
    "fg_01.before",
    /*      */"=> it when",
    /*      */"=> it then",
    /*      */"=> xit then and",
    /*      */"=> it then and",
    "fg_01.after",
    /*  */"\\ declare f02_steps_04 /",

    /**/"\\ declare feature_02 /",


    /**/"/ declare feature_03 \\",
    /*  */"/ declare f03_steps_01 \\",
    "fg_01.before",
    /*      */"=> it multi when",
    /*      */"=> it multi when",
    /*      */"=> it multi when",
    /*      */"=> it multi when",
    "fg_01.after",
    /*  */"\\ declare f03_steps_01 /",
    /**/"\\ declare feature_03 /",
    "\\ declare featureGroup_01 /",


    "/ declare feature_04 \\",
    /**/"/ declare f04_steps_01 \\",
    /*  */"=> it multi when",
    /*  */"=> it multi when",
    /*  */"=> it multi when",
    /*  */"=> it multi when",
    /**/"\\ declare f04_steps_01 /",

    /**/"/ declare f04_steps_02 \\",
    /*  */"=> it multi when",
    /*  */"=> it multi when",
    /*  */"=> it multi when",
    /*  */"=> it multi when",
    /**/"\\ declare f04_steps_02 /",
    "\\ declare feature_04 /",


    "/ declare featureGroup_01 \\",
    /**/"/ declare scenario_01 \\",
    "fg_01.before",
    "fg_01.after",
    /**/"\\ declare scenario_01 /",
    "\\ declare featureGroup_01 /",



    "/ declare scenario_02 \\",
    "\\ declare scenario_02 /"
];